# Search patterns for grouping paired samples in general stats (e.g. FastQ R1/R2)
# Affects the modules that support it (e.g. fastqc, fastp)
generalstats_sample_merge_groups:
  "R1": "_1"
  "R2": "_2"

module_order:
  - "cutadapt"
  - "fastqc":
      name: "FastQC: trimmed"
      anchor: "fqc_trimmed"
      path_filters:
        - "*_val*"
  - "fastqc":
      name: "FastQC: raw"
      anchor: "fqc_raw"
      path_filters_exclude:
        - "*_val*"
      generalstats: false
