repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.1.1
          - prettier-plugin-svelte@^3.1.2
          - prettier-plugin-astro@^0.12.3
          - prettier-plugin-organize-imports@^3.2.2
          - prettier-plugin-tailwindcss@^0.5.10
