[build]
  publish = "dist/"
  command = "git clone --depth 1 https://github.com/ewels/MultiQC.git ../MultiQC && npm run build"

[build.environment]
    NODE_VERSION = "18.14.0"

[[redirects]]
  from = "/version.php"
  to = "https://api.multiqc.info/version.php"
  status = 301
  force = true
