[build]
  publish = "dist/"
  command = "git clone --depth 1 https://github.com/MultiQC/MultiQC.git ../MultiQC && npm run build"

[build.environment]
    NODE_VERSION = "20.11.0"

[[redirects]]
  from = "/version.php"
  to = "https://api.multiqc.info/version.php"
  status = 301
  force = true

[[redirects]]
  from = "/docs/*"
  to = "https://docs.seqera.io/multiqc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/modules/*"
  to = "https://docs.seqera.io/multiqc/modules/:splat"
  status = 301
  force = true

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[[redirects]]
  from = "https://multiqc.netlify.app/*"
  to = "https://multiqc.info/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://multiqc.io/*"
  to = "https://multiqc.info/:splat"
  status = 301
  force = true

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  template = "hierarchical"
