fn_ignore_files:
    - '*.indel.annotated.vcf.gz.snpEff.summary.csv'

extra_fn_clean_exts:
    - ".clean"
    - ".AHJHNYCCXX"
    - pattern: _S\d_L00\d
      type: regex

extra_fn_clean_trim:
    - "_001"

# Search patterns for grouping paired samples in general stats (e.g. FastQ R1/R2)
# Affects the modules that support it (e.g. fastqc, fastp)
generalstats_sample_merge_groups:
  "R1": "_R1"
  "R2": "_R2"

table_columns_visible:
    FastQC:
        percent_duplicates: False
