# Build and push the Docker image for building the site (mkdocs material)

name: Build Astro dev docker image

on:
  push:
    # TODO: Update when merged to master
    branches: [astro]

jobs:
  astro_docker:
    if: github.repository == 'MultiQC/website'
    name: Build + push Astro docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build / push latest image
        uses: docker/build-push-action@v3
        with:
          # All available with node:lts-alpine are:
          # platforms: linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/s390x
          # But 32-bit binaries likely require compilation from source so stick with linux/amd64 and linux/arm64 for now
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/multiqc/website:latest
